### PR TITLE
Allow git to prompt user when calling send-email

### PR DESCRIPTION
**Pull request by frioux**
When I run `git send-email` git prompts me for some extra information, or maybe
it's just a confirmation.  This manifests itself as eternal blocking when it
comes to Git::CPAN::Patch, I think because of the way System::Command works.

I haven't been able to test this patch but I'm 90% sure it works.  If I get
a chance I'll do some more work to test it.

### CODE REVIEW

**Comment by frioux** [comment]
I tried to verify this patch with https://rt.cpan.org/Public/Bug/Display.html?id=106185.  I ended up needing to change the system call to exec and I changed it to use [my git wrapper](https://github.com/frioux/dotfiles/commit/2073088956dca22d7016bf5e04ed4ce97352e17b#diff-17214273c0b0468354f80fbabdd3172dR47) so that I wouldn't be prompted for a password.  I have no idea how to solve this generically :cry:

**Comment by frioux** [comment]
[I fixed my git-wrapper so that it is transparent](https://github.com/frioux/dotfiles/commit/d3b6011a39b1a82db7e80f8a968b2cb22dbad6fa), so I've updated the PR above such that it should work for everyone, myself included, I think.

**Comment by frioux** [comment]
Ok, so I finally think I have my head wrapped around this; feel free to comment or ping on irc:

1. Git may prompt for a password and that may be a desired behavior, so I still think this should be `exec`'d
2. Git by default will prompt the user if they really want to send.  You might want to override this by running with --confirm=never?  I'm not really sure.

I handled the password thing by adding an include file with my password in it: https://github.com/frioux/dotfiles/commit/80907cfaf84e94dc046315cc4353a245b35ba989.

Anyway I'll rebase my two patches.

**Comment by frioux** [comment]
(rebased)

**Comment by book** [comment]
Note that [System::Command 1.114](https://metacpan.org/release/BOOK/System-Command-1.114) has a new `interactive` option which sets up the proper environment for git, but calls `system`, thus allowing interactions with the user to happen.

Since Git::Repository transparently passes unknown options down to System::Command, you can use `interactive`, provided you ensure that System::Command is at least version 1.114.

**Pull request closed without merging**
